# site settings
title: Tashfiq
subtitle: Developer
email: tshfq.chw@gmail.com
description: A portfolio of all my work.
baseurl: /tashfooq.github.io # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Tashfiq Chowdhury
street_address: 31 Alderbrook
city: Irvine
state: CA
zip_code: 92604
country: United States of America
phone: (213) 421-6556

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/tashfooq 
linkedin_url: https://www.linkedin.com/in/ctashfiq 

# build settings
markdown: kramdown

sass:
  style: compressed
